Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: apagarRDS
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::886867172876:role/LabRole
      Code:
        ZipFile: |
          import boto3

          def lambda_handler(event, context):
              rds = boto3.client('rds')
              db_instance_identifier = 'FraudeBancoRDB'
              response = rds.stop_db_instance(DBInstanceIdentifier=db_instance_identifier)
              print(response)
      Runtime: python3.8